name: Generate Stego Image

on:
    push:
        branches:
            - right_here

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Install dependencies
              run: pip install pillow stegano
            - name: Generate image with hidden secret
              env:
                  HIDDEN_SECRET: ${{ secrets.IS_THIS_A_NEXT_CLUE }}
              run: python scripts/generate_stego_image.py
